### ISSUE TITLE
`<text>` element in XML serialization

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#72] opened 2023-12-18 12:31 UTC
There seem to be some inconsistencies about the use of a `<text>` element in serialization. Sometimes it is required (as a child of `<example>`) and sometimes not (as a child of `<definition>`) and the examples seem to mix this.

Is the idea that this is optional or can we clarify why it is used sometimes and other times not?

**Comment by DavidFatDavidF** [comment] 2024-04-03 13:30
@michmech this is now assigned to no one. How this will be addressed before the csd03 progression?

**Comment by DavidFatDavidF** [comment] 2024-04-04 09:29
To be clarified

**Comment by michmech** [comment] 2024-04-08 19:55
It's not random or arbitrary, there actually is a principle behind it. It's a `<text>` element if it can have siblings, and it's text content if not.

For example: a `<definition>` can contain only the text of the definition and no other child nodes, so it's text content:

```
<definition>Bla bla bla</definition>
```

whereas an `<example>` can contain not just the text of the example but also translations and labels, so there it's a `<text>`:

```
<example>
  <text>Bla bla bla.</text>
  <label tag="bla"/>
  <exampleTranslation>Ba bla bla.</exampleTranslation>
</example>
```

I've added some prose to section 5.1.1 'Design Principles' to clarify this.

**Comment by jmccrae** [comment] 2024-04-09 08:37
I am not sure that just clarifying the reason for this is a sufficient fix. My main concern is that we are not future-proof here, as the introduction of extra properties to a `definition` would then change the XML serialization in a breaking way.

My suggestion is that we do it all one way or another, with a preference for removing the `<text>` element entirely. e.g.,

```xml
<example>
  Bla bla bla.
  <label tag="bla"/>
  <exampleTranslation>Ba bla bla.</exampleTranslation>
</example>
```

**Comment by michmech** [comment] 2024-04-10 08:29
> My main concern is that we are not future-proof here, as the introduction of extra properties to a definition would then change the XML serialization in a breaking way.
> My suggestion is that we do it all one way or another [...]

You're right, this is a valid concern, I hadn't thought of that. This might be important if people want to create their own custom modules, and for our own future "DMLex version 2.0" maybe.

> with a preference for removing the `<text>` element entirely.

There I'm not so sure. If the text value has inline markup, then it becomes non-trivial to distinguish where the text value ends, you can't just grab the first text node:

```
<example>
  Bla <headwordMarker>bla</headwordMarker> bla.
  <label tag="bla"/>
  <exampleTranslation>Ba bla bla.</exampleTranslation>
</example>
```

With a `<text>` element it becomes more obvious where the text value is:

```
<example>
  <text>Bla <headwordMarker>bla</headwordMarker> bla.</text>
  <label tag="bla"/>
  <exampleTranslation>Ba bla bla.</exampleTranslation>
</example>
```

There is actually **no** good way to solve this problem in XML: we can either have it clear but verbose (my suggestion) or concise but unclear (your suggestion). I have written a whole paper about this, believe it or not: https://doi.org/10.1016/j.datak.2023.102196 ([preprint](https://www.lexiconista.com/pdf/better-than-xml.pdf)), see especially Section 5.2.

**Comment by jmccrae** [comment] 2024-04-10 09:35
I see that extracting the text out of an example is a bit harder without the `<text>` tag, but it is not very much harder as you just have to know to include the content of some tags (`<headwordMarker>`) and not others (`<exampleTranslation>`). I still have a preference for the `<text>`-less option but let's discuss tomorrow.

**Comment by DavidFatDavidF** [comment] 2024-04-10 13:57
It's normal for XML elements to contain a mixture of tags and plain text.
XML processors deal with that routinely.
A separate <text> element would only make business sense if it was
guaranteed that it will contain only plain text without any child tags.
Thus, I support John's push for <text>-less

**Comment by mjakubicek** [comment] 2024-04-10 14:04
Hm...I think that mixing tags and plain text in XML is rather a
malpractice, though syntactically valid.
I'm not having a very strong opinion about this because I do not see myself
as a future user of the XML serialization here, but I know that if I was, I
would hate it, as it almost always rules out using some simple non-XML
matching methods (grep and like) to extract data.

Best
Milos

st 10. 4. 2024 v 15:57 odesílatel dF ***@***.***> napsal:

> It's normal for XML elements to contain a mixture of tags and plain text.
> XML processors deal with that routinely.
> A separate <text> element would only make business sense if it was
> guaranteed that it will contain only plain text without any child tags.
> Thus, I support John's push for <text>-less
>

**Comment by DavidFatDavidF** [comment] 2024-04-10 14:59
Hm, it's not a malpractice, it is actually the default. [XML developed from
SGML that came about as a bunch of editorial tags over natural language
text ;-)]
It's of course a good practice to distinguish between structural and inline
tags when defining an XML vocabulary..
If you were a target user of the XML serialization you would use a stack of
reliable XML processors and not grep ;-)
A guaranteed plain text  <text> element (with any and all child tags
prohibited) would be an element targeting implementers of  your kind (read:
people who don't like to use XML as XML).
But I don't think we can guarantee that. Such an element could be at best
an auxiliary duplicate of the real data that can mix with tags..

**Comment by mjakubicek** [comment] 2024-04-10 20:07
Thanks -- that's exactly what I meant, and I'm so happy seeing you (again) explaining much better than myself.

**Comment by DavidFatDavidF** [comment] 2024-04-11 09:11
Consensus from meeting on 11th April:
Everywhere the model has a text property, XML has to implement <text>
->
Definition gets full option 3 treatment (it is fully extensible)
Transcription gets full option 3 treatment
Anything else

**Closed** 2024-04-18 08:07 UTC
Labels: editorial, serialization
